### PR TITLE
Update some wordings for release

### PR DESCRIPTION
**Pull request by Jordanlelay**
# Feature

### CODE REVIEW

**Comment by nicOwlas** [comment]
Good for me! I came back to the original default Stripe message, to avoid having some bad translations in some languages
> LabelFlow partners with Stripe for simplified billing.

**Comment by nacho-carnicero** [comment]
@nicOwlas please do not forget to perform the chromatic review when you merge stuff, otherwise we end up having visual changes in other PRs that have nothing to do with the changes done in that PR and it's confusing

**Comment by vincent-lecrubier-skydio** [comment]
> @nicOwlas please do not forget to perform the chromatic review when you merge stuff, otherwise we end up having visual changes in other PRs that have nothing to do with the changes done in that PR and it's confusing

You should not even be able to merge if there are unvalidated visual changes in chromatic, how was that possible ?

**Comment by nacho-carnicero** [comment]
Because he is an admin of the repo so he can skip the checks

**Comment by vincent-lecrubier-skydio** [comment]
> Because he is an admin of the repo so he can skip the checks

Yeah.... don’t do that... Checks are here for a reason.

**Comment by Jordanlelay** [comment]
> You should not even be able to merge if there are unvalidated visual changes in chromatic, how was that possible ?

The chromatic checks does not appear like required for me when I click `Merge pull request`, I don't have the warning saying something like `Use administrator privilege`. Maybe it's not enforce because we are not merging into main ?

**Comment by nicOwlas** [comment]
I did not have the warning asking me to `Use the administrator privilege`. The classical `Merge PR`. Also if I remember well, Chromatics tests appeared checked, which was not the case on the second PR I reviewed this morning (tutorial images) and for which I opened Chromatics to validate them.

**Pull request merged**
