### PR TITLE
Updates on export feature

### PR DESCRIPTION
**Pull request by etiennedupont**
# Feature

## Work performed

- Fixed a bug with images not having their referenced name with the "avoid name conflicts" option
- Ignored labels with undefined class
- Added a warning in the export modal in the case where there are some labels with an undefined class

### CODE REVIEW

**Comment by etiennedupont** [comment]
I am not satisfied with the look of the warning banner:

Screenshot 2021-09-16 at 17 57 35
Screenshot 2021-09-16 at 17 57 56

One thing I tried, but that I don't like either:

Screenshot 2021-09-16 at 18 15 49
Screenshot 2021-09-16 at 18 15 27

Looking for ideas @nicOwlas @crubier

**Comment by etiennedupont** [comment]
What I've reached so far, I let you give your opinion:

Screenshot 2021-09-17 at 14 57 18

Screenshot 2021-09-17 at 14 57 44

**Comment by nicOwlas** [comment]
Sorry for the delay. I'll have a look!

**Comment by nicOwlas** [comment]
More or less what you did on one of your screenshot. I don't find that bad tbh. I centered the alert between the subtitle and the COCO/YOLO export buttons and reduce the gap you had.

[Mockup link](https://www.figma.com/file/4J9xyfF5v4B98MuKVO0Y8V/LabelFlow-mockups?node-id=2798%3A9091)
image

**Comment by etiennedupont** [comment]
Thanks for the mockup! So just to recall: I drop the "info" alert back to what it was before?

**Comment by nicOwlas** [comment]
Yes but can you fix the vertical spacing?

**Comment by etiennedupont** [comment]
Of course, I'm on it

**Comment by etiennedupont** [comment]
What do you think @nicOwlas ?

Screenshot 2021-09-17 at 19 08 04

**Comment by nicOwlas** [comment]
Looking good!

**Comment by LouisAllen7** [comment]
@etiennedupont @nicOwlas Sorry for jumping on this late. 
Could we replace "None Class" with "Missing class"?

**Comment by etiennedupont** [comment]
I made the changes you asked for @nicOwlas @LouisAllen7. The only difference is that I added points everywhere instead of removing it at one place, it felt weird for a description with more than 1 phrase in it

**Review by crubier — APPROVED** [review]

**Pull request merged**
