### PR TITLE
Fix footer navigation links

### PR DESCRIPTION
**Pull request by waptik**
## Work performed

Added `passHref` to NextLink and removed `href` from chakra link so that the links will work as expected.
If it was done so intentionally, I'm really sorry.

## Results

Footer links should now work as expected.

## Problems encountered

Previously when you click on any of the links in the footer, you are being redirected back to the homepage.

### CODE REVIEW

**Comment by nicOwlas** [comment]
Whao, thank for you so much, we had not seen this bug. Thanks for the PR! 👍

**Review by bbenoist — CHANGES_REQUESTED** [review]
@waptik Thanks for the PR!

Linter is failing. See [this link](https://github.com/labelflow/labelflow/runs/5451198497?check_suite_focus=true#step:5:142) for details. If you want to reproduce the issue locally, you can run `yarn lint` from the root of the repository.

**Comment by waptik** [comment]
> @waptik Thanks for the PR!
> 
> Linter is failing. See [this link](https://github.com/labelflow/labelflow/runs/5451198497?check_suite_focus=true#step:5:142) for details. If you want to reproduce the issue locally, you can run `yarn lint` from the root of the repository.

Okay. I have to run `yarn install` in both the root and web folders before, right?

**Comment by bbenoist** [comment]
@waptik only running `yarn` at the root of the repository should be sufficient 😉

**Comment by waptik** [comment]
> @waptik only running `yarn` at the root of the repository should be sufficient 😉

Understood. I cloned my fork locally using `gh repo clone waptik/labelflow` but I can't find the `patch-1` branch. Can you help?

**Comment by Jordanlelay** [comment]
> Understood. I cloned my fork locally using `gh repo clone waptik/labelflow` but I can't find the `patch-1` branch. Can you help?

Hi @waptik , thanks for your contribution ! 
If you successfully cloned your repo, for switching to your branch, you should type in a terminal : 

```
git checkout patch-1
```

**Comment by waptik** [comment]
Thanks. That worked

**Comment by Jordanlelay** [comment]
> Thanks. That worked

Hi @waptik, do you need further help on fixing the linter problem ?

Without hearing from you in the next days, I will work on the issue you raised myself.
Thanks again for your contribution! 🙂

**Comment by waptik** [comment]
> > Thanks. That worked
> 
> Hi @waptik, do you need further help on fixing the linter problem ?
> 
> Without hearing from you in the next days, I will work on the issue you raised myself. Thanks again for your contribution! 🙂

Hi @Jordanlelay! Sorry I have been silent. I've been busy with other things.
I hit a roadblock after receiving help from you the other day. The roadblock is about some config issue with yarn when using `yarn` in the root folder. See the screenshot below.

So please do work on the issue yourself and tell me how to get past the issue with yarn so that I don't face the same issue again in the future.

image

**Comment by Jordanlelay** [comment]
Will be handled in #965

**Pull request closed without merging**
