### PR TITLE
Add Github button at two places in the website

### LINKED ISSUE #383: Add on labelflow website 2 links to github repo
**Tasks**
So to improve the visibility of LabelFlow being an open-source project. Add to the website following links:

- [ ] Add github icon to the right of `Blog` in the website navbar and direct to https://github.com/Labelflow
- [ ] `See code on github` button to the left of first `Try it now -->` call to action

image

### PR DESCRIPTION
**Pull request by etiennedupont**
# Feature

## Work performed

- The Github button was added according to #383's requirements
- The code was written once in `typescript/web/src/components/website/Navbar/NavContent.tsx` and imported in `typescript/web/src/components/website/Hero/Hero.tsx`

## Results

Screenshot 2021-08-30 at 18 01 06

## Resolved issues

Closes #383

### CODE REVIEW

**Comment by crubier** [comment]
The button is not visible in Mobile menu

Screenshot 2021-08-30 at 19 20 23

**Comment by crubier** [comment]
The buttons are spaced too far apart in this screen width 

Screenshot 2021-08-30 at 19 20 32

**Review by crubier — CHANGES_REQUESTED** [review]
Two UI issues to fix

**Comment by etiennedupont** [comment]
@crubier @nicOwlas What are your thoughts on that version?
I wonder whether the Github icon would be better placed on the right extremity?

Screenshot 2021-08-31 at 12 44 45


Screenshot 2021-08-31 at 12 44 57

**Comment by crubier** [comment]
> @crubier @nicOwlas What are your thoughts on that version?
> I wonder whether the Github icon would be better placed on the right extremity?
> 
> Screenshot 2021-08-31 at 12 44 45
> 
> Screenshot 2021-08-31 at 12 44 57

Nice, I think the icon is slightly too big, can probably change its size a bit. And maybe also a bit too far from the "Try now button" on the desktop version ? But good

**Comment by etiennedupont** [comment]
@crubier what about this version?

Screenshot 2021-08-31 at 13 01 06
Screenshot 2021-08-31 at 13 00 56

**Comment by crubier** [comment]
Nice

**Review by crubier — APPROVED** [review]

**Comment by nicOwlas** [comment]
👍

**Pull request merged**
