### PR TITLE
Change website NavBar GitHub link design (link version)

### LINKED ISSUE #759: Integrate a Star us on GitHub to the website
## Objective
Integrate a Star us on GitHub to the website. Have a call to action similar to supabase.com
image

## Tasks
- Two options:
  - https://ghbtns.com/
  - https://buttons.github.io/

## End result
Option A - Do not display the count but clear call to action. And triggers curiosity to go to GitHub to see the count
image

Option B - Display the count
image

### PR DESCRIPTION
**Pull request by bbenoist**
## Work performed

I've changed the design of the GitHub link button of the /website NavBar.

This is the link version, please choose between #760 and #761 or close both.

## Results

https://github.com/labelflow/labelflow/issues/759#issuecomment-1008924997

## Problems encountered

No

## Caveats

Takes more space in the NavBar

## Resolved issues

Closes #759 

## Newly raised issues

No

### CODE REVIEW

**Comment by nicOwlas** [comment]
I like this one better. Allows keeping a unique clear call to action (`try it now`) in the header.

**Comment by nicOwlas** [comment]
The link to GitHub does not work though

**Comment by bbenoist** [comment]
@nicOwlas It's fixed thanks for the info!

**Comment by valerian** [comment]
On mobile, we used to have the github link on the top right as an icon, but now it's in the dropdown menu only: should we keep the top right icon on mobile?
Screenshot 2022-01-11 at 10 52 25
Screenshot 2022-01-11 at 10 52 17

**Comment by bbenoist** [comment]
@valerian While the GitHub icon was OK, the star icon without its text was misleading and the most important action (_try it now_) was already in the menu so I made the mobile GUI look consistent (_IMO_).

**Comment by bbenoist** [comment]
@valerian Can you approve the PR if you're OK with it so that we can merge it right after #769 ?

**Review by valerian — APPROVED** [review]

**Comment by bbenoist** [comment]
Thanks for the trigorous review and approval @valerian 👍 
#769 is not yet ready, let's merge this PR and update #769 with @geoffreyvancassel once he'll back

**Comment by bbenoist** [comment]
Thanks for the rigorous review and approval @valerian 👍 
#769 is not yet ready, let's merge this PR and update #769 with @geoffreyvancassel once he'll back

**Pull request merged**
