### PR TITLE
Add tracking event to export button

### LINKED ISSUE #424: Add google analytics tracking event on the export (COCO / YOLO) format buttons
**Tasks**
In order to know how many exports are actually made (not clicks on the export button navbar), we want to add custom tracking events on the COCO & YOLO export buttons

- [x] Add custom tracking event on the coco export button
- [x] Add custom tracking event on the yolo export button

The event should be triggered when users actually clicks on "Export".

Blocked by #387

### PR DESCRIPTION
**Pull request by nacho-carnicero**
# Feature

## Work performed

- Added a tracking event when user clicks on export button (creates two events: `export_COCO_button_click` and `export_YOLO_button_click`)

## Results

The events show up in the google analytics dashboard as expected:
Screenshot 2021-09-24 at 11 08 00

Closes #424

### CODE REVIEW

**Comment by nicOwlas** [comment]
@nacho-carnicero not sure to get this right: you have different tracking events for each export format right? We want to track separately export / exportCoco / exportYolo.

**Comment by nacho-carnicero** [comment]
Yes as you can see in the screenshot there is one event for COCO export and another for YOLO export.

**Review by RaynalHugo — APPROVED** [review]

**Comment by nicOwlas** [comment]
`export_button_click_yolo`
`export_button_click_coco`
`export_button_click`

**Comment by nacho-carnicero** [comment]
Updated : 

Screenshot 2021-09-28 at 18 34 30

**Pull request merged**
